import streamlit as st
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import io
import matplotlib.pyplot as plt
from fpdf import FPDF

# ------------------ APP CONFIG ------------------
st.set_page_config(page_title="AI Resume Screener", layout="wide")
st.title("🤖 AI Resume Screener")
st.write("Upload your resume and paste a job description to see how well you match!")

# ------------------ FILE UPLOAD ------------------
uploaded_file = st.file_uploader("📂 Upload Resume (TXT or PDF)", type=["txt", "pdf"])
job_description = st.text_area("💼 Paste Job Description", height=200, placeholder="Paste the job description here...")

# ------------------ TEXT EXTRACTION ------------------
def extract_text_from_pdf(file):
    from PyPDF2 import PdfReader
    reader = PdfReader(file)
    text = ""
    for page in reader.pages:
        text += page.extract_text()
    return text

def clean_text(text):
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    return text.lower()

# ------------------ PDF REPORT FUNCTION ------------------
def generate_pdf_report(resume_name, score, skill_match_percent, matched_skills, job_skills, missing_skills, recommendation):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 16)
    pdf.cell(200, 10, txt="AI Resume Screening Report", ln=True, align="C")

    pdf.set_font("Arial", size=12)
    pdf.ln(10)
    pdf.cell(200, 10, txt=f"Resume File: {resume_name}", ln=True)
    pdf.cell(200, 10, txt=f"Overall Match Score: {score:.2f}%", ln=True)
    pdf.cell(200, 10, txt=f"Skill Match Score: {skill_match_percent:.2f}%", ln=True)
    pdf.ln(5)
    pdf.multi_cell(200, 10, txt=f"Matched Skills: {', '.join(matched_skills) if matched_skills else 'None'}")
    pdf.multi_cell(200, 10, txt=f"Required Skills: {', '.join(job_skills) if job_skills else 'None'}")
    pdf.multi_cell(200, 10, txt=f"Missing Skills: {', '.join(missing_skills) if missing_skills else 'None'}")
    pdf.ln(5)
    pdf.multi_cell(200, 10, txt=f"Recommendation: {recommendation}")
    pdf.ln(10)
    pdf.cell(200, 10, txt="Generated by AI Resume Screener", ln=True, align="C")

    pdf_bytes = pdf.output(dest='S').encode('latin1')
    return io.BytesIO(pdf_bytes)

# ------------------ ANALYSIS ------------------
if uploaded_file and job_description:

    # Extract resume text
    if uploaded_file.name.endswith(".pdf"):
        resume_text = extract_text_from_pdf(uploaded_file)
    else:
        resume_text = uploaded_file.read().decode("utf-8")

    resume_text = clean_text(resume_text)
    job_description = clean_text(job_description)

    # Skill extraction first (so score calc is accurate)
    common_skills = [
        "python", "java", "sql", "tableau", "power bi", "machine learning", "deep learning",
        "excel", "data analysis", "data visualization", "communication", "teamwork", "leadership",
        "django", "flask", "nlp", "docker", "aws", "git", "testing", "selenium",
        "html", "css", "javascript", "react", "node", "c++", "c#", "mongodb"
    ]

    resume_skills = [s for s in common_skills if s in resume_text]
    job_skills = [s for s in common_skills if s in job_description]
    matched_skills = [s for s in resume_skills if s in job_skills]
    missing_skills = [s for s in job_skills if s not in resume_skills]
    skill_match_percent = (len(matched_skills) / len(job_skills) * 100) if job_skills else 0

    # Textual similarity
    vectorizer = TfidfVectorizer(stop_words="english")
    vectors = vectorizer.fit_transform([resume_text, job_description])
    cosine_score = cosine_similarity(vectors[0:1], vectors[1:2])[0][0] * 100

    # Hybrid weighted score
    score = (0.6 * skill_match_percent) + (0.4 * cosine_score)

    # ------------------ DISPLAY RESULTS ------------------
    st.subheader("📊 Resume Evaluation Results")

    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("Overall Match Score (Hybrid)", f"{score:.2f}%")
    with col2:
        st.metric("Text Similarity", f"{cosine_score:.2f}%")
    with col3:
        st.metric("Skill Match Score", f"{skill_match_percent:.2f}%")

    # ------------------ PIE CHART ------------------
    st.divider()
    st.subheader("📈 Skill Match Breakdown")

    if job_skills:
        matched_count = len(matched_skills)
        missing_count = len(missing_skills)
        labels = ["Matched Skills", "Missing Skills"]
        sizes = [matched_count, missing_count]

        fig, ax = plt.subplots()
        ax.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=90)
        ax.axis("equal")
        st.pyplot(fig)
    else:
        st.info("No recognizable skills found in the job description.")

    # ------------------ Skill Lists ------------------
    st.write("### ✅ Matched Skills:", ", ".join(matched_skills) if matched_skills else "None")
    st.write("### ❌ Missing Skills:", ", ".join(missing_skills) if missing_skills else "None")

    # ------------------ Recommendation ------------------
    if score > 70 and len(missing_skills) < 3:
        recommendation = "Strong Match! Your resume aligns well with the job description."
        st.success(recommendation)
    elif score > 40:
        recommendation = f"Moderate Match. Consider adding: {', '.join(missing_skills) if missing_skills else 'more role-specific details.'}"
        st.warning(recommendation)
    else:
        recommendation = f"Weak Match. Add: {', '.join(missing_skills) if missing_skills else 'more relevant skills and keywords.'}"
        st.error(recommendation)

    # ------------------ DOWNLOAD REPORT ------------------
    st.divider()
    st.subheader("📥 Download Report")

    if st.button("Generate Report"):
        pdf_output = generate_pdf_report(
            uploaded_file.name,
            score,
            skill_match_percent,
            matched_skills,
            job_skills,
            missing_skills,
            recommendation
        )

        st.download_button(
            label="📄 Download PDF Report",
            data=pdf_output,
            file_name=f"{uploaded_file.name}_AI_Report.pdf",
            mime="application/pdf"
        )

else:
    st.info("👆 Upload a resume and paste a job description to begin analysis.")